// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6i7PNF4l4KalIq1Z9xsstJPDlYwIqujQ',
    appId: '1:276926171898:web:d350bd90d3c4e0edf79743',
    messagingSenderId: '276926171898',
    projectId: 'flutter-iot-esp32',
    authDomain: 'flutter-iot-esp32.firebaseapp.com',
    storageBucket: 'flutter-iot-esp32.firebasestorage.app',
    measurementId: 'G-7DK6E7CHQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO_yqCnwbv6SBjWGxaJ-sDq9-myeiqsXg',
    appId: '1:276926171898:android:b2bb91f66e3711c8f79743',
    messagingSenderId: '276926171898',
    projectId: 'flutter-iot-esp32',
    storageBucket: 'flutter-iot-esp32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFdjA_Adgusk_1Ad2PJvCej7G8t6Upe_c',
    appId: '1:276926171898:ios:54594a9036ada402f79743',
    messagingSenderId: '276926171898',
    projectId: 'flutter-iot-esp32',
    storageBucket: 'flutter-iot-esp32.firebasestorage.app',
    iosBundleId: 'com.flutter.iot.esp32.ust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFdjA_Adgusk_1Ad2PJvCej7G8t6Upe_c',
    appId: '1:276926171898:ios:0b544ccd231bbaacf79743',
    messagingSenderId: '276926171898',
    projectId: 'flutter-iot-esp32',
    storageBucket: 'flutter-iot-esp32.firebasestorage.app',
    iosBundleId: 'com.example.flutterIotEsp32Ust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6i7PNF4l4KalIq1Z9xsstJPDlYwIqujQ',
    appId: '1:276926171898:web:8f68fbdd918c8e50f79743',
    messagingSenderId: '276926171898',
    projectId: 'flutter-iot-esp32',
    authDomain: 'flutter-iot-esp32.firebaseapp.com',
    storageBucket: 'flutter-iot-esp32.firebasestorage.app',
    measurementId: 'G-8BLQZ3LH9S',
  );
}
